[package]
name = "ecms_acl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecms_control_graph = { path = '../ewal_control_graph' }
serde = "1.0.103"
serde_json = "1.0.80"
serde_derive = "1.0.103"
