//! Round-trip: `FormData` -> typed `Fieldset` struct -> `clean()` -> `FormData`.
//!
//! Demonstrates the typed <-> dynamic interop bridge generated by
//! `#[fieldset(into_form_data, try_from_form_data)]`. Use this pattern when an
//! HTTP layer hands you an untyped `FormData` payload but the rest of your
//! code wants a strongly-typed struct (and vice versa).
//!
//! Run with:
//!   cargo run --example derive_formdata_bridge -p walrs_form

#![allow(deprecated)]

use walrs_fieldfilter::{DeriveFieldset, Fieldset};
use walrs_form::FormData;
use walrs_validation::Value;

#[derive(Debug, DeriveFieldset)]
#[fieldset(into_form_data, try_from_form_data)]
struct Signup {
  #[validate(required, email)]
  #[filter(trim, lowercase)]
  email: String,

  #[validate(required, min_length = 8)]
  password: String,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
  // 1. Dynamic input from an HTTP layer (untyped key/value bag).
  let mut incoming = FormData::new();
  incoming.insert("email", Value::Str("  Alice@Example.COM  ".to_string()));
  incoming.insert("password", Value::Str("hunter2hunter2".to_string()));

  // 2. Bridge: dynamic FormData -> typed struct (TryFrom impl is generated).
  let signup = Signup::try_from(incoming)?;
  println!("typed (raw):    {:?}", signup);

  // 3. Apply filters and validate per-field via the Fieldset trait.
  let cleaned = signup.clean()?;
  println!("typed (clean):  {:?}", cleaned);

  // 4. Bridge back: typed struct -> dynamic FormData (From<&T> impl is generated).
  let outgoing: FormData = (&cleaned).into();
  println!("back to FormData:");
  for (k, v) in outgoing.iter() {
    println!("  {} = {:?}", k, v);
  }

  Ok(())
}
